# .bash_profile
# vim:sts=4 sw=4 et
# Bash shell per-login initialisation
# Copyright 2015-2018 Andrew Bettison

# Work out where shellboost is installed and bootstrap shellboost's include
# system.  If readlink(1) is not installed, this will fail and fall back to
# the logic in .profile
__env_bash_profile="$(readlink -q -e "${BASH_SOURCE[0]}" 2>/dev/null)" 2>/dev/null
export SHELLBOOST="${__env_bash_profile%/env/bash_profile}"
unset __env_bash_profile
if [ -f "$SHELLBOOST/libsh/include.sh" ]; then
    source "$SHELLBOOST/libsh/include.sh"
else
    unset SHELLBOOST
    __shellboost_include() { echo "Failure: __shellboost_include $1" >&2; return 1; }
fi

# Source initialisation scripts.
test -r "$HOME/.bashrc" && source "$HOME/.bashrc"
test -r "$HOME/.profile" && source "$HOME/.profile"

# Source current development profile, if there is one.
case $(builtin type -t init_devprofile) in
function)
    init_devprofile
    ;;
esac

# User specific environment and startup programs
unset USERNAME

# Bash command history
shopt -s histappend # append to .bash_history file, don't overwrite
export HISTCONTROL=ignoreboth # don't store lines that start with space or are duplicates
export HISTSIZE=1000000 # keep a lot of history
export HISTFILESIZE=1000000

# ABO settings
if [ -r "$ABO_HOME/env/bash_profile" ]; then
    source "$ABO_HOME/env/bash_profile"
fi
