# .bash_profile
# vim:sts=4 sw=4 et
# Bash shell per-login initialisation
# Copyright 2015-2016 Andrew Bettison

# Work out where shellboost is installed and bootstrap shellboost's include
# system.  If readlink(1) is not installed, this will fail and fall back to
# the logic in .profile
__env_bash_profile="$(readlink -q -e "${BASH_SOURCE[0]}" 2>/dev/null)" 2>/dev/null
export SHELLBOOST="${__env_bash_profile%/env/bash_profile}"
unset __env_bash_profile
if [ -f "$SHELLBOOST/libsh/include.sh" ]; then
    source "$SHELLBOOST/libsh/include.sh"
else
    unset SHELLBOOST
    __shellboost_include() { echo "Failure: __shellboost_include $1" >&2; return 1; }
fi

# Source initialisation scripts.
test -r "$HOME/.bashrc" && source "$HOME/.bashrc"
test -r "$HOME/.profile" && source "$HOME/.profile"

# Source current development profile, if there is one.
case $(builtin type -t _init_current_devprofile) in
function)
    _init_current_devprofile
    ;;
esac

# User specific environment and startup programs

unset USERNAME
export HISTSIZE=1000000 # keep a lot of history

# ABO settings
[ -r "$ABO_HOME/env/bash_profile" ] && source "$ABO_HOME/env/bash_profile"
